// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Auth.proto

package dal_core

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Authorities struct {
	OrgAuthorities       []*OrgAuthority  `protobuf:"bytes,1,rep,name=org_authorities,json=orgAuthorities,proto3" json:"org_authorities,omitempty"`
	UserAuthorities      []*UserAuthority `protobuf:"bytes,2,rep,name=user_authorities,json=userAuthorities,proto3" json:"user_authorities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Authorities) Reset()         { *m = Authorities{} }
func (m *Authorities) String() string { return proto.CompactTextString(m) }
func (*Authorities) ProtoMessage()    {}
func (*Authorities) Descriptor() ([]byte, []int) {
	return fileDescriptor_0be2fdcb97a9c409, []int{0}
}

func (m *Authorities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authorities.Unmarshal(m, b)
}
func (m *Authorities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authorities.Marshal(b, m, deterministic)
}
func (m *Authorities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authorities.Merge(m, src)
}
func (m *Authorities) XXX_Size() int {
	return xxx_messageInfo_Authorities.Size(m)
}
func (m *Authorities) XXX_DiscardUnknown() {
	xxx_messageInfo_Authorities.DiscardUnknown(m)
}

var xxx_messageInfo_Authorities proto.InternalMessageInfo

func (m *Authorities) GetOrgAuthorities() []*OrgAuthority {
	if m != nil {
		return m.OrgAuthorities
	}
	return nil
}

func (m *Authorities) GetUserAuthorities() []*UserAuthority {
	if m != nil {
		return m.UserAuthorities
	}
	return nil
}

type UserAuthority struct {
	OrgAuthKey           string   `protobuf:"bytes,1,opt,name=org_auth_key,json=orgAuthKey,proto3" json:"org_auth_key,omitempty"`
	UserAuthKey          string   `protobuf:"bytes,2,opt,name=user_auth_key,json=userAuthKey,proto3" json:"user_auth_key,omitempty"`
	UserAuthValue        int64    `protobuf:"varint,3,opt,name=user_auth_value,json=userAuthValue,proto3" json:"user_auth_value,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserAuthority) Reset()         { *m = UserAuthority{} }
func (m *UserAuthority) String() string { return proto.CompactTextString(m) }
func (*UserAuthority) ProtoMessage()    {}
func (*UserAuthority) Descriptor() ([]byte, []int) {
	return fileDescriptor_0be2fdcb97a9c409, []int{1}
}

func (m *UserAuthority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserAuthority.Unmarshal(m, b)
}
func (m *UserAuthority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserAuthority.Marshal(b, m, deterministic)
}
func (m *UserAuthority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserAuthority.Merge(m, src)
}
func (m *UserAuthority) XXX_Size() int {
	return xxx_messageInfo_UserAuthority.Size(m)
}
func (m *UserAuthority) XXX_DiscardUnknown() {
	xxx_messageInfo_UserAuthority.DiscardUnknown(m)
}

var xxx_messageInfo_UserAuthority proto.InternalMessageInfo

func (m *UserAuthority) GetOrgAuthKey() string {
	if m != nil {
		return m.OrgAuthKey
	}
	return ""
}

func (m *UserAuthority) GetUserAuthKey() string {
	if m != nil {
		return m.UserAuthKey
	}
	return ""
}

func (m *UserAuthority) GetUserAuthValue() int64 {
	if m != nil {
		return m.UserAuthValue
	}
	return 0
}

func (m *UserAuthority) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type OrgAuthority struct {
	OrgAuthKey           string   `protobuf:"bytes,1,opt,name=org_auth_key,json=orgAuthKey,proto3" json:"org_auth_key,omitempty"`
	OrgAuthValue         int64    `protobuf:"varint,2,opt,name=org_auth_value,json=orgAuthValue,proto3" json:"org_auth_value,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrgAuthority) Reset()         { *m = OrgAuthority{} }
func (m *OrgAuthority) String() string { return proto.CompactTextString(m) }
func (*OrgAuthority) ProtoMessage()    {}
func (*OrgAuthority) Descriptor() ([]byte, []int) {
	return fileDescriptor_0be2fdcb97a9c409, []int{2}
}

func (m *OrgAuthority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgAuthority.Unmarshal(m, b)
}
func (m *OrgAuthority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgAuthority.Marshal(b, m, deterministic)
}
func (m *OrgAuthority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgAuthority.Merge(m, src)
}
func (m *OrgAuthority) XXX_Size() int {
	return xxx_messageInfo_OrgAuthority.Size(m)
}
func (m *OrgAuthority) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgAuthority.DiscardUnknown(m)
}

var xxx_messageInfo_OrgAuthority proto.InternalMessageInfo

func (m *OrgAuthority) GetOrgAuthKey() string {
	if m != nil {
		return m.OrgAuthKey
	}
	return ""
}

func (m *OrgAuthority) GetOrgAuthValue() int64 {
	if m != nil {
		return m.OrgAuthValue
	}
	return 0
}

func (m *OrgAuthority) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Authorities)(nil), "dal_core.Authorities")
	proto.RegisterType((*UserAuthority)(nil), "dal_core.UserAuthority")
	proto.RegisterType((*OrgAuthority)(nil), "dal_core.OrgAuthority")
}

func init() { proto.RegisterFile("Auth.proto", fileDescriptor_0be2fdcb97a9c409) }

var fileDescriptor_0be2fdcb97a9c409 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0x87, 0xdf, 0x34, 0xe5, 0x45, 0xa7, 0xff, 0x64, 0xc1, 0x1a, 0xdb, 0x4b, 0x08, 0x22, 0x3d,
	0x6d, 0xa1, 0x7e, 0x00, 0x69, 0xd5, 0x93, 0x07, 0xa1, 0xa2, 0x1e, 0x4b, 0x1a, 0xc7, 0x35, 0x9a,
	0x3a, 0x61, 0xb3, 0x29, 0xe4, 0x63, 0xe8, 0x27, 0x96, 0xdd, 0x76, 0xbb, 0xc9, 0xcd, 0x5b, 0x76,
	0x78, 0xe6, 0xf9, 0x4d, 0x66, 0x00, 0xe6, 0xa5, 0x7a, 0xe7, 0xb9, 0x24, 0x45, 0xec, 0xe8, 0x35,
	0xce, 0x56, 0x09, 0x49, 0x1c, 0x8d, 0x05, 0x91, 0xc8, 0x70, 0x6a, 0xea, 0xeb, 0xf2, 0x6d, 0x8a,
	0x9b, 0x5c, 0x55, 0x3b, 0x2c, 0xfa, 0xf1, 0xa0, 0xa3, 0xbb, 0x48, 0xa6, 0x2a, 0xc5, 0x82, 0x5d,
	0xc3, 0x80, 0xa4, 0x58, 0xc5, 0xae, 0x14, 0x78, 0xa1, 0x3f, 0xe9, 0xcc, 0x86, 0xdc, 0x0a, 0xf9,
	0x83, 0x14, 0xb6, 0xa5, 0x5a, 0xf6, 0xc9, 0xbd, 0xb4, 0x60, 0x01, 0x27, 0x65, 0x81, 0xb2, 0x61,
	0x68, 0x19, 0xc3, 0x99, 0x33, 0x3c, 0x15, 0x28, 0x9d, 0x62, 0x50, 0xd6, 0x9e, 0x29, 0x16, 0xd1,
	0xb7, 0x07, 0xbd, 0x06, 0xc2, 0x42, 0xe8, 0xda, 0xb1, 0x56, 0x9f, 0x58, 0x05, 0x5e, 0xe8, 0x4d,
	0x8e, 0x97, 0xb0, 0xcf, 0xbe, 0xc7, 0x8a, 0x45, 0xd0, 0x3b, 0xe4, 0x1a, 0xa4, 0x65, 0x90, 0x8e,
	0x75, 0x6b, 0xe6, 0x12, 0x06, 0x8e, 0xd9, 0xc6, 0x59, 0x89, 0x81, 0x1f, 0x7a, 0x13, 0x7f, 0xd9,
	0xb3, 0xd4, 0xb3, 0x2e, 0x32, 0x06, 0xed, 0xaf, 0x78, 0x83, 0x41, 0xdb, 0x28, 0xcc, 0x77, 0xf4,
	0x01, 0xdd, 0xfa, 0x7f, 0xff, 0x61, 0xa2, 0x0b, 0xe8, 0x1f, 0x88, 0x5d, 0x58, 0xcb, 0x84, 0x75,
	0xf7, 0x4c, 0x33, 0xcb, 0x77, 0x59, 0xb3, 0x17, 0x60, 0xb7, 0x71, 0x76, 0x43, 0x12, 0x35, 0xf7,
	0x88, 0x72, 0x9b, 0x26, 0xc8, 0xe6, 0xd0, 0x17, 0xa8, 0xea, 0xbb, 0x1e, 0xf2, 0xdd, 0x69, 0xb9,
	0x3d, 0x2d, 0xbf, 0xd3, 0xa7, 0x1d, 0x9d, 0xba, 0x4d, 0xd7, 0xd7, 0xfa, 0x6f, 0x31, 0x86, 0xf3,
	0x84, 0x36, 0x7c, 0x4d, 0xa4, 0xe2, 0x3c, 0xd7, 0x14, 0x37, 0x94, 0x90, 0x79, 0xb2, 0xfe, 0x6f,
	0x2c, 0x57, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x07, 0x3a, 0xb2, 0x44, 0x46, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DalCoreAuthServiceClient is the client API for DalCoreAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DalCoreAuthServiceClient interface {
	//------------------ User
	// check login
	GetAuthorities(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Authorities, error)
}

type dalCoreAuthServiceClient struct {
	cc *grpc.ClientConn
}

func NewDalCoreAuthServiceClient(cc *grpc.ClientConn) DalCoreAuthServiceClient {
	return &dalCoreAuthServiceClient{cc}
}

func (c *dalCoreAuthServiceClient) GetAuthorities(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Authorities, error) {
	out := new(Authorities)
	err := c.cc.Invoke(ctx, "/dal_core.DalCoreAuthService/getAuthorities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DalCoreAuthServiceServer is the server API for DalCoreAuthService service.
type DalCoreAuthServiceServer interface {
	//------------------ User
	// check login
	GetAuthorities(context.Context, *empty.Empty) (*Authorities, error)
}

func RegisterDalCoreAuthServiceServer(s *grpc.Server, srv DalCoreAuthServiceServer) {
	s.RegisterService(&_DalCoreAuthService_serviceDesc, srv)
}

func _DalCoreAuthService_GetAuthorities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DalCoreAuthServiceServer).GetAuthorities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dal_core.DalCoreAuthService/GetAuthorities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DalCoreAuthServiceServer).GetAuthorities(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _DalCoreAuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dal_core.DalCoreAuthService",
	HandlerType: (*DalCoreAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getAuthorities",
			Handler:    _DalCoreAuthService_GetAuthorities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Auth.proto",
}
