// Code generated by protoc-gen-go. DO NOT EDIT.
// source: core_common.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//===================================== Common Types
type EntityStatus int32

const (
	EntityStatus_ENTITY_STATUS_NULL        EntityStatus = 0
	EntityStatus_ENTITY_STATUS_NORMAL      EntityStatus = 1
	EntityStatus_ENTITY_STATUS_DELETED     EntityStatus = 2
	EntityStatus_ENTITY_STATUS_INACTIVATED EntityStatus = 3
	EntityStatus_ENTITY_STATUS_DEPRECATED  EntityStatus = 4
	EntityStatus_ENTITY_STATUS_SUBMITTED   EntityStatus = 5
	EntityStatus_ENTITY_STATUS_PROCESSING  EntityStatus = 6
	EntityStatus_ENTITY_STATUS_DONE        EntityStatus = 7
)

var EntityStatus_name = map[int32]string{
	0: "ENTITY_STATUS_NULL",
	1: "ENTITY_STATUS_NORMAL",
	2: "ENTITY_STATUS_DELETED",
	3: "ENTITY_STATUS_INACTIVATED",
	4: "ENTITY_STATUS_DEPRECATED",
	5: "ENTITY_STATUS_SUBMITTED",
	6: "ENTITY_STATUS_PROCESSING",
	7: "ENTITY_STATUS_DONE",
}

var EntityStatus_value = map[string]int32{
	"ENTITY_STATUS_NULL":        0,
	"ENTITY_STATUS_NORMAL":      1,
	"ENTITY_STATUS_DELETED":     2,
	"ENTITY_STATUS_INACTIVATED": 3,
	"ENTITY_STATUS_DEPRECATED":  4,
	"ENTITY_STATUS_SUBMITTED":   5,
	"ENTITY_STATUS_PROCESSING":  6,
	"ENTITY_STATUS_DONE":        7,
}

func (x EntityStatus) String() string {
	return proto.EnumName(EntityStatus_name, int32(x))
}

func (EntityStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{0}
}

type Language int32

const (
	Language_LANG_NULL  Language = 0
	Language_LANG_ZH_CN Language = 1
)

var Language_name = map[int32]string{
	0: "LANG_NULL",
	1: "LANG_ZH_CN",
}

var Language_value = map[string]int32{
	"LANG_NULL":  0,
	"LANG_ZH_CN": 1,
}

func (x Language) String() string {
	return proto.EnumName(Language_name, int32(x))
}

func (Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{1}
}

type Country int32

const (
	Country_COUNTRY_NULL  Country = 0
	Country_COUNTRY_CHINA Country = 1
)

var Country_name = map[int32]string{
	0: "COUNTRY_NULL",
	1: "COUNTRY_CHINA",
}

var Country_value = map[string]int32{
	"COUNTRY_NULL":  0,
	"COUNTRY_CHINA": 1,
}

func (x Country) String() string {
	return proto.EnumName(Country_name, int32(x))
}

func (Country) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{2}
}

type AuthType int32

const (
	AuthType_AUTH_TYPE_NULL  AuthType = 0
	AuthType_AUTH_TYPE_READ  AuthType = 1
	AuthType_AUTH_TYPE_WRITE AuthType = 2
)

var AuthType_name = map[int32]string{
	0: "AUTH_TYPE_NULL",
	1: "AUTH_TYPE_READ",
	2: "AUTH_TYPE_WRITE",
}

var AuthType_value = map[string]int32{
	"AUTH_TYPE_NULL":  0,
	"AUTH_TYPE_READ":  1,
	"AUTH_TYPE_WRITE": 2,
}

func (x AuthType) String() string {
	return proto.EnumName(AuthType_name, int32(x))
}

func (AuthType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{3}
}

type UpdateType int32

const (
	UpdateType_UPDATE_TYPE_NULL    UpdateType = 0
	UpdateType_UPDATE_TYPE_REPLACE UpdateType = 1
	UpdateType_UPDATE_TYPE_APPEND  UpdateType = 2
)

var UpdateType_name = map[int32]string{
	0: "UPDATE_TYPE_NULL",
	1: "UPDATE_TYPE_REPLACE",
	2: "UPDATE_TYPE_APPEND",
}

var UpdateType_value = map[string]int32{
	"UPDATE_TYPE_NULL":    0,
	"UPDATE_TYPE_REPLACE": 1,
	"UPDATE_TYPE_APPEND":  2,
}

func (x UpdateType) String() string {
	return proto.EnumName(UpdateType_name, int32(x))
}

func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{4}
}

type SortType int32

const (
	SortType_SORT_TYPE_NULL      SortType = 0
	SortType_SORT_TYPE_TIME_ASC  SortType = 1
	SortType_SORT_TYPE_TIME_DESC SortType = 2
	SortType_SORT_TYPE_ID_ASC    SortType = 3
	SortType_SORT_TYPE_ID_DESC   SortType = 4
)

var SortType_name = map[int32]string{
	0: "SORT_TYPE_NULL",
	1: "SORT_TYPE_TIME_ASC",
	2: "SORT_TYPE_TIME_DESC",
	3: "SORT_TYPE_ID_ASC",
	4: "SORT_TYPE_ID_DESC",
}

var SortType_value = map[string]int32{
	"SORT_TYPE_NULL":      0,
	"SORT_TYPE_TIME_ASC":  1,
	"SORT_TYPE_TIME_DESC": 2,
	"SORT_TYPE_ID_ASC":    3,
	"SORT_TYPE_ID_DESC":   4,
}

func (x SortType) String() string {
	return proto.EnumName(SortType_name, int32(x))
}

func (SortType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{5}
}

// =========================================== Message
type MessageType int32

const (
	MessageType_MESSAGE_TYPE_NULL MessageType = 0
	MessageType_MESSAGE_TYPE_ORG  MessageType = 1
	MessageType_MESSAGE_TYPE_USER MessageType = 2
)

var MessageType_name = map[int32]string{
	0: "MESSAGE_TYPE_NULL",
	1: "MESSAGE_TYPE_ORG",
	2: "MESSAGE_TYPE_USER",
}

var MessageType_value = map[string]int32{
	"MESSAGE_TYPE_NULL": 0,
	"MESSAGE_TYPE_ORG":  1,
	"MESSAGE_TYPE_USER": 2,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}

func (MessageType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{6}
}

type ReceiveType int32

const (
	ReceiveType_RECEIVE_TYPE_NULL  ReceiveType = 0
	ReceiveType_RECEIVE_TYPE_SITE  ReceiveType = 1
	ReceiveType_RECEIVE_TYPE_EMAIL ReceiveType = 2
	ReceiveType_RECEIVE_TYPE_SMS   ReceiveType = 3
)

var ReceiveType_name = map[int32]string{
	0: "RECEIVE_TYPE_NULL",
	1: "RECEIVE_TYPE_SITE",
	2: "RECEIVE_TYPE_EMAIL",
	3: "RECEIVE_TYPE_SMS",
}

var ReceiveType_value = map[string]int32{
	"RECEIVE_TYPE_NULL":  0,
	"RECEIVE_TYPE_SITE":  1,
	"RECEIVE_TYPE_EMAIL": 2,
	"RECEIVE_TYPE_SMS":   3,
}

func (x ReceiveType) String() string {
	return proto.EnumName(ReceiveType_name, int32(x))
}

func (ReceiveType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{7}
}

// ========================================== Relations
type RelationType int32

const (
	RelationType_RELATION_NULL                       RelationType = 0
	RelationType_RELATION_ORG_USER_PARTNER_SUPPLIER  RelationType = 1
	RelationType_RELATION_ORG_USER_PARTNER_LOGISTICS RelationType = 2
)

var RelationType_name = map[int32]string{
	0: "RELATION_NULL",
	1: "RELATION_ORG_USER_PARTNER_SUPPLIER",
	2: "RELATION_ORG_USER_PARTNER_LOGISTICS",
}

var RelationType_value = map[string]int32{
	"RELATION_NULL":                       0,
	"RELATION_ORG_USER_PARTNER_SUPPLIER":  1,
	"RELATION_ORG_USER_PARTNER_LOGISTICS": 2,
}

func (x RelationType) String() string {
	return proto.EnumName(RelationType_name, int32(x))
}

func (RelationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{8}
}

type Pagination struct {
	Idx                  int64    `protobuf:"varint,1,opt,name=idx,proto3" json:"idx,omitempty"`
	Size                 int64    `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sort                 SortType `protobuf:"varint,3,opt,name=sort,proto3,enum=core.SortType" json:"sort,omitempty"`
	Total                int64    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{0}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetIdx() int64 {
	if m != nil {
		return m.Idx
	}
	return 0
}

func (m *Pagination) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Pagination) GetSort() SortType {
	if m != nil {
		return m.Sort
	}
	return SortType_SORT_TYPE_NULL
}

func (m *Pagination) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

type AuthorizedPaginationReq struct {
	UserId               int64       `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId                int64       `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AuthorizedPaginationReq) Reset()         { *m = AuthorizedPaginationReq{} }
func (m *AuthorizedPaginationReq) String() string { return proto.CompactTextString(m) }
func (*AuthorizedPaginationReq) ProtoMessage()    {}
func (*AuthorizedPaginationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{1}
}

func (m *AuthorizedPaginationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizedPaginationReq.Unmarshal(m, b)
}
func (m *AuthorizedPaginationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizedPaginationReq.Marshal(b, m, deterministic)
}
func (m *AuthorizedPaginationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizedPaginationReq.Merge(m, src)
}
func (m *AuthorizedPaginationReq) XXX_Size() int {
	return xxx_messageInfo_AuthorizedPaginationReq.Size(m)
}
func (m *AuthorizedPaginationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizedPaginationReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizedPaginationReq proto.InternalMessageInfo

func (m *AuthorizedPaginationReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AuthorizedPaginationReq) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *AuthorizedPaginationReq) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type IdQueryReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdQueryReq) Reset()         { *m = IdQueryReq{} }
func (m *IdQueryReq) String() string { return proto.CompactTextString(m) }
func (*IdQueryReq) ProtoMessage()    {}
func (*IdQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{2}
}

func (m *IdQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdQueryReq.Unmarshal(m, b)
}
func (m *IdQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdQueryReq.Marshal(b, m, deterministic)
}
func (m *IdQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdQueryReq.Merge(m, src)
}
func (m *IdQueryReq) XXX_Size() int {
	return xxx_messageInfo_IdQueryReq.Size(m)
}
func (m *IdQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IdQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_IdQueryReq proto.InternalMessageInfo

func (m *IdQueryReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type AuthorizedIdQueryReq struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId                int64    `protobuf:"varint,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizedIdQueryReq) Reset()         { *m = AuthorizedIdQueryReq{} }
func (m *AuthorizedIdQueryReq) String() string { return proto.CompactTextString(m) }
func (*AuthorizedIdQueryReq) ProtoMessage()    {}
func (*AuthorizedIdQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{3}
}

func (m *AuthorizedIdQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizedIdQueryReq.Unmarshal(m, b)
}
func (m *AuthorizedIdQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizedIdQueryReq.Marshal(b, m, deterministic)
}
func (m *AuthorizedIdQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizedIdQueryReq.Merge(m, src)
}
func (m *AuthorizedIdQueryReq) XXX_Size() int {
	return xxx_messageInfo_AuthorizedIdQueryReq.Size(m)
}
func (m *AuthorizedIdQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizedIdQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizedIdQueryReq proto.InternalMessageInfo

func (m *AuthorizedIdQueryReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AuthorizedIdQueryReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AuthorizedIdQueryReq) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

type PaginatedIdQueryReq struct {
	Id                   int64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PaginatedIdQueryReq) Reset()         { *m = PaginatedIdQueryReq{} }
func (m *PaginatedIdQueryReq) String() string { return proto.CompactTextString(m) }
func (*PaginatedIdQueryReq) ProtoMessage()    {}
func (*PaginatedIdQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{4}
}

func (m *PaginatedIdQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginatedIdQueryReq.Unmarshal(m, b)
}
func (m *PaginatedIdQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginatedIdQueryReq.Marshal(b, m, deterministic)
}
func (m *PaginatedIdQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginatedIdQueryReq.Merge(m, src)
}
func (m *PaginatedIdQueryReq) XXX_Size() int {
	return xxx_messageInfo_PaginatedIdQueryReq.Size(m)
}
func (m *PaginatedIdQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginatedIdQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_PaginatedIdQueryReq proto.InternalMessageInfo

func (m *PaginatedIdQueryReq) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *PaginatedIdQueryReq) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type PaginatedIdsQueryReq struct {
	Ids                  []int64     `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PaginatedIdsQueryReq) Reset()         { *m = PaginatedIdsQueryReq{} }
func (m *PaginatedIdsQueryReq) String() string { return proto.CompactTextString(m) }
func (*PaginatedIdsQueryReq) ProtoMessage()    {}
func (*PaginatedIdsQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{5}
}

func (m *PaginatedIdsQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PaginatedIdsQueryReq.Unmarshal(m, b)
}
func (m *PaginatedIdsQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PaginatedIdsQueryReq.Marshal(b, m, deterministic)
}
func (m *PaginatedIdsQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PaginatedIdsQueryReq.Merge(m, src)
}
func (m *PaginatedIdsQueryReq) XXX_Size() int {
	return xxx_messageInfo_PaginatedIdsQueryReq.Size(m)
}
func (m *PaginatedIdsQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PaginatedIdsQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_PaginatedIdsQueryReq proto.InternalMessageInfo

func (m *PaginatedIdsQueryReq) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *PaginatedIdsQueryReq) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type IdsQueryReq struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdsQueryReq) Reset()         { *m = IdsQueryReq{} }
func (m *IdsQueryReq) String() string { return proto.CompactTextString(m) }
func (*IdsQueryReq) ProtoMessage()    {}
func (*IdsQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{6}
}

func (m *IdsQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdsQueryReq.Unmarshal(m, b)
}
func (m *IdsQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdsQueryReq.Marshal(b, m, deterministic)
}
func (m *IdsQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdsQueryReq.Merge(m, src)
}
func (m *IdsQueryReq) XXX_Size() int {
	return xxx_messageInfo_IdsQueryReq.Size(m)
}
func (m *IdsQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IdsQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_IdsQueryReq proto.InternalMessageInfo

func (m *IdsQueryReq) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type AuthorizedIdsQueryReq struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId                int64    `protobuf:"varint,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorizedIdsQueryReq) Reset()         { *m = AuthorizedIdsQueryReq{} }
func (m *AuthorizedIdsQueryReq) String() string { return proto.CompactTextString(m) }
func (*AuthorizedIdsQueryReq) ProtoMessage()    {}
func (*AuthorizedIdsQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{7}
}

func (m *AuthorizedIdsQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizedIdsQueryReq.Unmarshal(m, b)
}
func (m *AuthorizedIdsQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizedIdsQueryReq.Marshal(b, m, deterministic)
}
func (m *AuthorizedIdsQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizedIdsQueryReq.Merge(m, src)
}
func (m *AuthorizedIdsQueryReq) XXX_Size() int {
	return xxx_messageInfo_AuthorizedIdsQueryReq.Size(m)
}
func (m *AuthorizedIdsQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizedIdsQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizedIdsQueryReq proto.InternalMessageInfo

func (m *AuthorizedIdsQueryReq) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *AuthorizedIdsQueryReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AuthorizedIdsQueryReq) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

type StringQueryReq struct {
	Query                string      `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StringQueryReq) Reset()         { *m = StringQueryReq{} }
func (m *StringQueryReq) String() string { return proto.CompactTextString(m) }
func (*StringQueryReq) ProtoMessage()    {}
func (*StringQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{8}
}

func (m *StringQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringQueryReq.Unmarshal(m, b)
}
func (m *StringQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringQueryReq.Marshal(b, m, deterministic)
}
func (m *StringQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringQueryReq.Merge(m, src)
}
func (m *StringQueryReq) XXX_Size() int {
	return xxx_messageInfo_StringQueryReq.Size(m)
}
func (m *StringQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StringQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_StringQueryReq proto.InternalMessageInfo

func (m *StringQueryReq) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *StringQueryReq) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type AuthorizedStringQueryReq struct {
	Query                string      `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	UserId               int64       `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId                int64       `protobuf:"varint,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,4,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AuthorizedStringQueryReq) Reset()         { *m = AuthorizedStringQueryReq{} }
func (m *AuthorizedStringQueryReq) String() string { return proto.CompactTextString(m) }
func (*AuthorizedStringQueryReq) ProtoMessage()    {}
func (*AuthorizedStringQueryReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{9}
}

func (m *AuthorizedStringQueryReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorizedStringQueryReq.Unmarshal(m, b)
}
func (m *AuthorizedStringQueryReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorizedStringQueryReq.Marshal(b, m, deterministic)
}
func (m *AuthorizedStringQueryReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorizedStringQueryReq.Merge(m, src)
}
func (m *AuthorizedStringQueryReq) XXX_Size() int {
	return xxx_messageInfo_AuthorizedStringQueryReq.Size(m)
}
func (m *AuthorizedStringQueryReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorizedStringQueryReq.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorizedStringQueryReq proto.InternalMessageInfo

func (m *AuthorizedStringQueryReq) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *AuthorizedStringQueryReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AuthorizedStringQueryReq) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *AuthorizedStringQueryReq) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{10}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type StringsResp struct {
	Data                 []string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringsResp) Reset()         { *m = StringsResp{} }
func (m *StringsResp) String() string { return proto.CompactTextString(m) }
func (*StringsResp) ProtoMessage()    {}
func (*StringsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{11}
}

func (m *StringsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringsResp.Unmarshal(m, b)
}
func (m *StringsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringsResp.Marshal(b, m, deterministic)
}
func (m *StringsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringsResp.Merge(m, src)
}
func (m *StringsResp) XXX_Size() int {
	return xxx_messageInfo_StringsResp.Size(m)
}
func (m *StringsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StringsResp.DiscardUnknown(m)
}

var xxx_messageInfo_StringsResp proto.InternalMessageInfo

func (m *StringsResp) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

// =========================================== User
type User struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId                int64                 `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Status               EntityStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=core.EntityStatus" json:"status,omitempty"`
	Phone                *wrappers.StringValue `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                *wrappers.StringValue `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Username             *wrappers.StringValue `protobuf:"bytes,6,opt,name=username,proto3" json:"username,omitempty"`
	Password             *wrappers.StringValue `protobuf:"bytes,7,opt,name=password,proto3" json:"password,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	CreateAt             int64                 `protobuf:"varint,9,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt             int64                 `protobuf:"varint,10,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{12}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *User) GetStatus() EntityStatus {
	if m != nil {
		return m.Status
	}
	return EntityStatus_ENTITY_STATUS_NULL
}

func (m *User) GetPhone() *wrappers.StringValue {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *User) GetEmail() *wrappers.StringValue {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *User) GetUsername() *wrappers.StringValue {
	if m != nil {
		return m.Username
	}
	return nil
}

func (m *User) GetPassword() *wrappers.StringValue {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *User) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *User) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *User) GetUpdateAt() int64 {
	if m != nil {
		return m.UpdateAt
	}
	return 0
}

type OrgWithAuthorities struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AuthorityGroups      string   `protobuf:"bytes,3,opt,name=authority_groups,json=authorityGroups,proto3" json:"authority_groups,omitempty"`
	Authorities          string   `protobuf:"bytes,4,opt,name=authorities,proto3" json:"authorities,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrgWithAuthorities) Reset()         { *m = OrgWithAuthorities{} }
func (m *OrgWithAuthorities) String() string { return proto.CompactTextString(m) }
func (*OrgWithAuthorities) ProtoMessage()    {}
func (*OrgWithAuthorities) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{13}
}

func (m *OrgWithAuthorities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgWithAuthorities.Unmarshal(m, b)
}
func (m *OrgWithAuthorities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgWithAuthorities.Marshal(b, m, deterministic)
}
func (m *OrgWithAuthorities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgWithAuthorities.Merge(m, src)
}
func (m *OrgWithAuthorities) XXX_Size() int {
	return xxx_messageInfo_OrgWithAuthorities.Size(m)
}
func (m *OrgWithAuthorities) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgWithAuthorities.DiscardUnknown(m)
}

var xxx_messageInfo_OrgWithAuthorities proto.InternalMessageInfo

func (m *OrgWithAuthorities) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrgWithAuthorities) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrgWithAuthorities) GetAuthorityGroups() string {
	if m != nil {
		return m.AuthorityGroups
	}
	return ""
}

func (m *OrgWithAuthorities) GetAuthorities() string {
	if m != nil {
		return m.Authorities
	}
	return ""
}

type UserWithOrgAuth struct {
	User                 *User                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	OrgInfo              []*OrgWithAuthorities `protobuf:"bytes,2,rep,name=org_info,json=orgInfo,proto3" json:"org_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UserWithOrgAuth) Reset()         { *m = UserWithOrgAuth{} }
func (m *UserWithOrgAuth) String() string { return proto.CompactTextString(m) }
func (*UserWithOrgAuth) ProtoMessage()    {}
func (*UserWithOrgAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{14}
}

func (m *UserWithOrgAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserWithOrgAuth.Unmarshal(m, b)
}
func (m *UserWithOrgAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserWithOrgAuth.Marshal(b, m, deterministic)
}
func (m *UserWithOrgAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserWithOrgAuth.Merge(m, src)
}
func (m *UserWithOrgAuth) XXX_Size() int {
	return xxx_messageInfo_UserWithOrgAuth.Size(m)
}
func (m *UserWithOrgAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_UserWithOrgAuth.DiscardUnknown(m)
}

var xxx_messageInfo_UserWithOrgAuth proto.InternalMessageInfo

func (m *UserWithOrgAuth) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserWithOrgAuth) GetOrgInfo() []*OrgWithAuthorities {
	if m != nil {
		return m.OrgInfo
	}
	return nil
}

type UserWithOrgInfo struct {
	User                 *User           `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Orgs                 []*Organization `protobuf:"bytes,2,rep,name=orgs,proto3" json:"orgs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserWithOrgInfo) Reset()         { *m = UserWithOrgInfo{} }
func (m *UserWithOrgInfo) String() string { return proto.CompactTextString(m) }
func (*UserWithOrgInfo) ProtoMessage()    {}
func (*UserWithOrgInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{15}
}

func (m *UserWithOrgInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserWithOrgInfo.Unmarshal(m, b)
}
func (m *UserWithOrgInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserWithOrgInfo.Marshal(b, m, deterministic)
}
func (m *UserWithOrgInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserWithOrgInfo.Merge(m, src)
}
func (m *UserWithOrgInfo) XXX_Size() int {
	return xxx_messageInfo_UserWithOrgInfo.Size(m)
}
func (m *UserWithOrgInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserWithOrgInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserWithOrgInfo proto.InternalMessageInfo

func (m *UserWithOrgInfo) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserWithOrgInfo) GetOrgs() []*Organization {
	if m != nil {
		return m.Orgs
	}
	return nil
}

type UsersResp struct {
	Data                 []*User     `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UsersResp) Reset()         { *m = UsersResp{} }
func (m *UsersResp) String() string { return proto.CompactTextString(m) }
func (*UsersResp) ProtoMessage()    {}
func (*UsersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{16}
}

func (m *UsersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UsersResp.Unmarshal(m, b)
}
func (m *UsersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UsersResp.Marshal(b, m, deterministic)
}
func (m *UsersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UsersResp.Merge(m, src)
}
func (m *UsersResp) XXX_Size() int {
	return xxx_messageInfo_UsersResp.Size(m)
}
func (m *UsersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UsersResp.DiscardUnknown(m)
}

var xxx_messageInfo_UsersResp proto.InternalMessageInfo

func (m *UsersResp) GetData() []*User {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *UsersResp) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// =========================================== Org
type Organization struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string       `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	OrgRoleId            int64        `protobuf:"varint,3,opt,name=org_role_id,json=orgRoleId,proto3" json:"org_role_id,omitempty"`
	Name                 string       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Status               EntityStatus `protobuf:"varint,5,opt,name=status,proto3,enum=core.EntityStatus" json:"status,omitempty"`
	CreateAt             int64        `protobuf:"varint,6,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt             int64        `protobuf:"varint,7,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Organization) Reset()         { *m = Organization{} }
func (m *Organization) String() string { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()    {}
func (*Organization) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{17}
}

func (m *Organization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Organization.Unmarshal(m, b)
}
func (m *Organization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Organization.Marshal(b, m, deterministic)
}
func (m *Organization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Organization.Merge(m, src)
}
func (m *Organization) XXX_Size() int {
	return xxx_messageInfo_Organization.Size(m)
}
func (m *Organization) XXX_DiscardUnknown() {
	xxx_messageInfo_Organization.DiscardUnknown(m)
}

var xxx_messageInfo_Organization proto.InternalMessageInfo

func (m *Organization) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Organization) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Organization) GetOrgRoleId() int64 {
	if m != nil {
		return m.OrgRoleId
	}
	return 0
}

func (m *Organization) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Organization) GetStatus() EntityStatus {
	if m != nil {
		return m.Status
	}
	return EntityStatus_ENTITY_STATUS_NULL
}

func (m *Organization) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *Organization) GetUpdateAt() int64 {
	if m != nil {
		return m.UpdateAt
	}
	return 0
}

type OrganizationEdit struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	OrgRoleId            *wrappers.Int64Value  `protobuf:"bytes,3,opt,name=org_role_id,json=orgRoleId,proto3" json:"org_role_id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Status               EntityStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=core.EntityStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *OrganizationEdit) Reset()         { *m = OrganizationEdit{} }
func (m *OrganizationEdit) String() string { return proto.CompactTextString(m) }
func (*OrganizationEdit) ProtoMessage()    {}
func (*OrganizationEdit) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{18}
}

func (m *OrganizationEdit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrganizationEdit.Unmarshal(m, b)
}
func (m *OrganizationEdit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrganizationEdit.Marshal(b, m, deterministic)
}
func (m *OrganizationEdit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrganizationEdit.Merge(m, src)
}
func (m *OrganizationEdit) XXX_Size() int {
	return xxx_messageInfo_OrganizationEdit.Size(m)
}
func (m *OrganizationEdit) XXX_DiscardUnknown() {
	xxx_messageInfo_OrganizationEdit.DiscardUnknown(m)
}

var xxx_messageInfo_OrganizationEdit proto.InternalMessageInfo

func (m *OrganizationEdit) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrganizationEdit) GetCode() *wrappers.StringValue {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *OrganizationEdit) GetOrgRoleId() *wrappers.Int64Value {
	if m != nil {
		return m.OrgRoleId
	}
	return nil
}

func (m *OrganizationEdit) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *OrganizationEdit) GetStatus() EntityStatus {
	if m != nil {
		return m.Status
	}
	return EntityStatus_ENTITY_STATUS_NULL
}

type OrgsResp struct {
	Data                 []*Organization `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination           *Pagination     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *OrgsResp) Reset()         { *m = OrgsResp{} }
func (m *OrgsResp) String() string { return proto.CompactTextString(m) }
func (*OrgsResp) ProtoMessage()    {}
func (*OrgsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{19}
}

func (m *OrgsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrgsResp.Unmarshal(m, b)
}
func (m *OrgsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrgsResp.Marshal(b, m, deterministic)
}
func (m *OrgsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrgsResp.Merge(m, src)
}
func (m *OrgsResp) XXX_Size() int {
	return xxx_messageInfo_OrgsResp.Size(m)
}
func (m *OrgsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_OrgsResp.DiscardUnknown(m)
}

var xxx_messageInfo_OrgsResp proto.InternalMessageInfo

func (m *OrgsResp) GetData() []*Organization {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *OrgsResp) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type Message struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 MessageType           `protobuf:"varint,2,opt,name=type,proto3,enum=core.MessageType" json:"type,omitempty"`
	ReceiveType          ReceiveType           `protobuf:"varint,3,opt,name=receive_type,json=receiveType,proto3,enum=core.ReceiveType" json:"receive_type,omitempty"`
	OrgId                int64                 `protobuf:"varint,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	UserId               int64                 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	To                   int64                 `protobuf:"varint,6,opt,name=to,proto3" json:"to,omitempty"`
	Title                *wrappers.StringValue `protobuf:"bytes,7,opt,name=title,proto3" json:"title,omitempty"`
	Content              *wrappers.StringValue `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	Files                *wrappers.StringValue `protobuf:"bytes,9,opt,name=files,proto3" json:"files,omitempty"`
	Status               EntityStatus          `protobuf:"varint,10,opt,name=status,proto3,enum=core.EntityStatus" json:"status,omitempty"`
	CreateAt             int64                 `protobuf:"varint,11,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt             int64                 `protobuf:"varint,12,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	ContactInfo          *wrappers.StringValue `protobuf:"bytes,20,opt,name=contact_info,json=contactInfo,proto3" json:"contact_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{20}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_MESSAGE_TYPE_NULL
}

func (m *Message) GetReceiveType() ReceiveType {
	if m != nil {
		return m.ReceiveType
	}
	return ReceiveType_RECEIVE_TYPE_NULL
}

func (m *Message) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *Message) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Message) GetTo() int64 {
	if m != nil {
		return m.To
	}
	return 0
}

func (m *Message) GetTitle() *wrappers.StringValue {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *Message) GetContent() *wrappers.StringValue {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Message) GetFiles() *wrappers.StringValue {
	if m != nil {
		return m.Files
	}
	return nil
}

func (m *Message) GetStatus() EntityStatus {
	if m != nil {
		return m.Status
	}
	return EntityStatus_ENTITY_STATUS_NULL
}

func (m *Message) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *Message) GetUpdateAt() int64 {
	if m != nil {
		return m.UpdateAt
	}
	return 0
}

func (m *Message) GetContactInfo() *wrappers.StringValue {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

type MessageResp struct {
	Data                 []*Message  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *MessageResp) Reset()         { *m = MessageResp{} }
func (m *MessageResp) String() string { return proto.CompactTextString(m) }
func (*MessageResp) ProtoMessage()    {}
func (*MessageResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{21}
}

func (m *MessageResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResp.Unmarshal(m, b)
}
func (m *MessageResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResp.Marshal(b, m, deterministic)
}
func (m *MessageResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResp.Merge(m, src)
}
func (m *MessageResp) XXX_Size() int {
	return xxx_messageInfo_MessageResp.Size(m)
}
func (m *MessageResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResp.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResp proto.InternalMessageInfo

func (m *MessageResp) GetData() []*Message {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MessageResp) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type Relation struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SourceId             int64                 `protobuf:"varint,2,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId             int64                 `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Type                 RelationType          `protobuf:"varint,4,opt,name=type,proto3,enum=core.RelationType" json:"type,omitempty"`
	AttachedId1          int64                 `protobuf:"varint,5,opt,name=attached_id1,json=attachedId1,proto3" json:"attached_id1,omitempty"`
	AttachedId2          int64                 `protobuf:"varint,6,opt,name=attached_id2,json=attachedId2,proto3" json:"attached_id2,omitempty"`
	Value1               *wrappers.StringValue `protobuf:"bytes,7,opt,name=value1,proto3" json:"value1,omitempty"`
	Value2               *wrappers.StringValue `protobuf:"bytes,8,opt,name=value2,proto3" json:"value2,omitempty"`
	Status               EntityStatus          `protobuf:"varint,9,opt,name=status,proto3,enum=core.EntityStatus" json:"status,omitempty"`
	CreateAt             int64                 `protobuf:"varint,10,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt             int64                 `protobuf:"varint,11,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Relation) Reset()         { *m = Relation{} }
func (m *Relation) String() string { return proto.CompactTextString(m) }
func (*Relation) ProtoMessage()    {}
func (*Relation) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{22}
}

func (m *Relation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Relation.Unmarshal(m, b)
}
func (m *Relation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Relation.Marshal(b, m, deterministic)
}
func (m *Relation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Relation.Merge(m, src)
}
func (m *Relation) XXX_Size() int {
	return xxx_messageInfo_Relation.Size(m)
}
func (m *Relation) XXX_DiscardUnknown() {
	xxx_messageInfo_Relation.DiscardUnknown(m)
}

var xxx_messageInfo_Relation proto.InternalMessageInfo

func (m *Relation) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Relation) GetSourceId() int64 {
	if m != nil {
		return m.SourceId
	}
	return 0
}

func (m *Relation) GetTargetId() int64 {
	if m != nil {
		return m.TargetId
	}
	return 0
}

func (m *Relation) GetType() RelationType {
	if m != nil {
		return m.Type
	}
	return RelationType_RELATION_NULL
}

func (m *Relation) GetAttachedId1() int64 {
	if m != nil {
		return m.AttachedId1
	}
	return 0
}

func (m *Relation) GetAttachedId2() int64 {
	if m != nil {
		return m.AttachedId2
	}
	return 0
}

func (m *Relation) GetValue1() *wrappers.StringValue {
	if m != nil {
		return m.Value1
	}
	return nil
}

func (m *Relation) GetValue2() *wrappers.StringValue {
	if m != nil {
		return m.Value2
	}
	return nil
}

func (m *Relation) GetStatus() EntityStatus {
	if m != nil {
		return m.Status
	}
	return EntityStatus_ENTITY_STATUS_NULL
}

func (m *Relation) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *Relation) GetUpdateAt() int64 {
	if m != nil {
		return m.UpdateAt
	}
	return 0
}

type RelationsResp struct {
	Relations            []*Relation `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	Pagination           *Pagination `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *RelationsResp) Reset()         { *m = RelationsResp{} }
func (m *RelationsResp) String() string { return proto.CompactTextString(m) }
func (*RelationsResp) ProtoMessage()    {}
func (*RelationsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{23}
}

func (m *RelationsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RelationsResp.Unmarshal(m, b)
}
func (m *RelationsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RelationsResp.Marshal(b, m, deterministic)
}
func (m *RelationsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RelationsResp.Merge(m, src)
}
func (m *RelationsResp) XXX_Size() int {
	return xxx_messageInfo_RelationsResp.Size(m)
}
func (m *RelationsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RelationsResp.DiscardUnknown(m)
}

var xxx_messageInfo_RelationsResp proto.InternalMessageInfo

func (m *RelationsResp) GetRelations() []*Relation {
	if m != nil {
		return m.Relations
	}
	return nil
}

func (m *RelationsResp) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type PartnersResp struct {
	Relations            []*Relation                `protobuf:"bytes,1,rep,name=relations,proto3" json:"relations,omitempty"`
	Pagination           *Pagination                `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	UserMap              map[int64]*UserWithOrgInfo `protobuf:"bytes,3,rep,name=user_map,json=userMap,proto3" json:"user_map,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *PartnersResp) Reset()         { *m = PartnersResp{} }
func (m *PartnersResp) String() string { return proto.CompactTextString(m) }
func (*PartnersResp) ProtoMessage()    {}
func (*PartnersResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{24}
}

func (m *PartnersResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartnersResp.Unmarshal(m, b)
}
func (m *PartnersResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartnersResp.Marshal(b, m, deterministic)
}
func (m *PartnersResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartnersResp.Merge(m, src)
}
func (m *PartnersResp) XXX_Size() int {
	return xxx_messageInfo_PartnersResp.Size(m)
}
func (m *PartnersResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PartnersResp.DiscardUnknown(m)
}

var xxx_messageInfo_PartnersResp proto.InternalMessageInfo

func (m *PartnersResp) GetRelations() []*Relation {
	if m != nil {
		return m.Relations
	}
	return nil
}

func (m *PartnersResp) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func (m *PartnersResp) GetUserMap() map[int64]*UserWithOrgInfo {
	if m != nil {
		return m.UserMap
	}
	return nil
}

// =========================================== Dept
type DepartmentEdit struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid                  int64                 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	OrgId                int64                 `protobuf:"varint,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Remark               *wrappers.StringValue `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	Status               EntityStatus          `protobuf:"varint,7,opt,name=status,proto3,enum=core.EntityStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *DepartmentEdit) Reset()         { *m = DepartmentEdit{} }
func (m *DepartmentEdit) String() string { return proto.CompactTextString(m) }
func (*DepartmentEdit) ProtoMessage()    {}
func (*DepartmentEdit) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{25}
}

func (m *DepartmentEdit) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepartmentEdit.Unmarshal(m, b)
}
func (m *DepartmentEdit) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepartmentEdit.Marshal(b, m, deterministic)
}
func (m *DepartmentEdit) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartmentEdit.Merge(m, src)
}
func (m *DepartmentEdit) XXX_Size() int {
	return xxx_messageInfo_DepartmentEdit.Size(m)
}
func (m *DepartmentEdit) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartmentEdit.DiscardUnknown(m)
}

var xxx_messageInfo_DepartmentEdit proto.InternalMessageInfo

func (m *DepartmentEdit) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *DepartmentEdit) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *DepartmentEdit) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *DepartmentEdit) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *DepartmentEdit) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *DepartmentEdit) GetRemark() *wrappers.StringValue {
	if m != nil {
		return m.Remark
	}
	return nil
}

func (m *DepartmentEdit) GetStatus() EntityStatus {
	if m != nil {
		return m.Status
	}
	return EntityStatus_ENTITY_STATUS_NULL
}

type Department struct {
	Id                   int64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid                  int64        `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	OrgId                int64        `protobuf:"varint,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Name                 string       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Description          string       `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Remark               string       `protobuf:"bytes,6,opt,name=remark,proto3" json:"remark,omitempty"`
	Status               EntityStatus `protobuf:"varint,7,opt,name=status,proto3,enum=core.EntityStatus" json:"status,omitempty"`
	CreateAt             int64        `protobuf:"varint,8,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdateAt             int64        `protobuf:"varint,9,opt,name=update_at,json=updateAt,proto3" json:"update_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Department) Reset()         { *m = Department{} }
func (m *Department) String() string { return proto.CompactTextString(m) }
func (*Department) ProtoMessage()    {}
func (*Department) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{26}
}

func (m *Department) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Department.Unmarshal(m, b)
}
func (m *Department) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Department.Marshal(b, m, deterministic)
}
func (m *Department) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Department.Merge(m, src)
}
func (m *Department) XXX_Size() int {
	return xxx_messageInfo_Department.Size(m)
}
func (m *Department) XXX_DiscardUnknown() {
	xxx_messageInfo_Department.DiscardUnknown(m)
}

var xxx_messageInfo_Department proto.InternalMessageInfo

func (m *Department) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Department) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *Department) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *Department) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Department) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Department) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *Department) GetStatus() EntityStatus {
	if m != nil {
		return m.Status
	}
	return EntityStatus_ENTITY_STATUS_NULL
}

func (m *Department) GetCreateAt() int64 {
	if m != nil {
		return m.CreateAt
	}
	return 0
}

func (m *Department) GetUpdateAt() int64 {
	if m != nil {
		return m.UpdateAt
	}
	return 0
}

type DeptsResp struct {
	Data                 []*Department `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination           *Pagination   `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DeptsResp) Reset()         { *m = DeptsResp{} }
func (m *DeptsResp) String() string { return proto.CompactTextString(m) }
func (*DeptsResp) ProtoMessage()    {}
func (*DeptsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_6bccad1a36ca954c, []int{27}
}

func (m *DeptsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeptsResp.Unmarshal(m, b)
}
func (m *DeptsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeptsResp.Marshal(b, m, deterministic)
}
func (m *DeptsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeptsResp.Merge(m, src)
}
func (m *DeptsResp) XXX_Size() int {
	return xxx_messageInfo_DeptsResp.Size(m)
}
func (m *DeptsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_DeptsResp.DiscardUnknown(m)
}

var xxx_messageInfo_DeptsResp proto.InternalMessageInfo

func (m *DeptsResp) GetData() []*Department {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *DeptsResp) GetPagination() *Pagination {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterEnum("core.EntityStatus", EntityStatus_name, EntityStatus_value)
	proto.RegisterEnum("core.Language", Language_name, Language_value)
	proto.RegisterEnum("core.Country", Country_name, Country_value)
	proto.RegisterEnum("core.AuthType", AuthType_name, AuthType_value)
	proto.RegisterEnum("core.UpdateType", UpdateType_name, UpdateType_value)
	proto.RegisterEnum("core.SortType", SortType_name, SortType_value)
	proto.RegisterEnum("core.MessageType", MessageType_name, MessageType_value)
	proto.RegisterEnum("core.ReceiveType", ReceiveType_name, ReceiveType_value)
	proto.RegisterEnum("core.RelationType", RelationType_name, RelationType_value)
	proto.RegisterType((*Pagination)(nil), "core.Pagination")
	proto.RegisterType((*AuthorizedPaginationReq)(nil), "core.AuthorizedPaginationReq")
	proto.RegisterType((*IdQueryReq)(nil), "core.IdQueryReq")
	proto.RegisterType((*AuthorizedIdQueryReq)(nil), "core.AuthorizedIdQueryReq")
	proto.RegisterType((*PaginatedIdQueryReq)(nil), "core.PaginatedIdQueryReq")
	proto.RegisterType((*PaginatedIdsQueryReq)(nil), "core.PaginatedIdsQueryReq")
	proto.RegisterType((*IdsQueryReq)(nil), "core.IdsQueryReq")
	proto.RegisterType((*AuthorizedIdsQueryReq)(nil), "core.AuthorizedIdsQueryReq")
	proto.RegisterType((*StringQueryReq)(nil), "core.StringQueryReq")
	proto.RegisterType((*AuthorizedStringQueryReq)(nil), "core.AuthorizedStringQueryReq")
	proto.RegisterType((*Empty)(nil), "core.Empty")
	proto.RegisterType((*StringsResp)(nil), "core.StringsResp")
	proto.RegisterType((*User)(nil), "core.User")
	proto.RegisterType((*OrgWithAuthorities)(nil), "core.OrgWithAuthorities")
	proto.RegisterType((*UserWithOrgAuth)(nil), "core.UserWithOrgAuth")
	proto.RegisterType((*UserWithOrgInfo)(nil), "core.UserWithOrgInfo")
	proto.RegisterType((*UsersResp)(nil), "core.UsersResp")
	proto.RegisterType((*Organization)(nil), "core.Organization")
	proto.RegisterType((*OrganizationEdit)(nil), "core.OrganizationEdit")
	proto.RegisterType((*OrgsResp)(nil), "core.OrgsResp")
	proto.RegisterType((*Message)(nil), "core.Message")
	proto.RegisterType((*MessageResp)(nil), "core.MessageResp")
	proto.RegisterType((*Relation)(nil), "core.Relation")
	proto.RegisterType((*RelationsResp)(nil), "core.RelationsResp")
	proto.RegisterType((*PartnersResp)(nil), "core.PartnersResp")
	proto.RegisterMapType((map[int64]*UserWithOrgInfo)(nil), "core.PartnersResp.UserMapEntry")
	proto.RegisterType((*DepartmentEdit)(nil), "core.DepartmentEdit")
	proto.RegisterType((*Department)(nil), "core.Department")
	proto.RegisterType((*DeptsResp)(nil), "core.DeptsResp")
}

func init() { proto.RegisterFile("core_common.proto", fileDescriptor_6bccad1a36ca954c) }

var fileDescriptor_6bccad1a36ca954c = []byte{
	// 1713 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x58, 0xdd, 0x8e, 0xdb, 0xc6,
	0x15, 0x2e, 0x29, 0x69, 0x25, 0x1d, 0xc9, 0x32, 0x77, 0xbc, 0x6b, 0x2b, 0xb1, 0xeb, 0xac, 0xd5,
	0xd6, 0x75, 0xd4, 0x62, 0x63, 0x2b, 0x46, 0x10, 0xa4, 0x40, 0x0b, 0x46, 0x22, 0xd6, 0x04, 0xf4,
	0xe7, 0x21, 0x65, 0x77, 0x03, 0x14, 0x02, 0x2d, 0xce, 0xca, 0x84, 0x25, 0x92, 0x19, 0x8e, 0x92,
	0xca, 0xed, 0x6d, 0x5f, 0xa0, 0xe8, 0x6d, 0x2f, 0xfa, 0x3e, 0x7d, 0x93, 0x5e, 0xf4, 0xba, 0x17,
	0x05, 0x8a, 0x99, 0xa1, 0x44, 0x52, 0xda, 0x1f, 0xad, 0x80, 0xde, 0x51, 0xe7, 0x7c, 0xe7, 0x77,
	0xbe, 0x73, 0x66, 0x76, 0xe1, 0x70, 0x12, 0x50, 0x32, 0x9e, 0x04, 0xf3, 0x79, 0xe0, 0x9f, 0x86,
	0x34, 0x60, 0x01, 0xca, 0x73, 0xd1, 0xa7, 0x8f, 0xa7, 0x41, 0x30, 0x9d, 0x91, 0x2f, 0x84, 0xec,
	0xdd, 0xe2, 0xe2, 0x8b, 0x1f, 0xa9, 0x13, 0x86, 0x84, 0x46, 0x12, 0xd5, 0x98, 0x01, 0x0c, 0x9d,
	0xa9, 0xe7, 0x3b, 0xcc, 0x0b, 0x7c, 0xa4, 0x41, 0xce, 0x73, 0xff, 0x58, 0x57, 0x4e, 0x94, 0x67,
	0x39, 0xcc, 0x3f, 0x11, 0x82, 0x7c, 0xe4, 0x7d, 0x24, 0x75, 0x55, 0x88, 0xc4, 0x37, 0x6a, 0x40,
	0x3e, 0x0a, 0x28, 0xab, 0xe7, 0x4e, 0x94, 0x67, 0xb5, 0x56, 0xed, 0x94, 0x07, 0x3a, 0xb5, 0x02,
	0xca, 0xec, 0x65, 0x48, 0xb0, 0xd0, 0xa1, 0x23, 0x28, 0xb0, 0x80, 0x39, 0xb3, 0x7a, 0x5e, 0x18,
	0xca, 0x1f, 0x8d, 0x3f, 0xc1, 0x03, 0x7d, 0xc1, 0xde, 0x07, 0xd4, 0xfb, 0x48, 0xdc, 0x24, 0x2e,
	0x26, 0xdf, 0xa3, 0x07, 0x50, 0x5c, 0x44, 0x84, 0x8e, 0x3d, 0x37, 0x0e, 0x7f, 0xc0, 0x7f, 0x9a,
	0x2e, 0x3a, 0x86, 0x83, 0x80, 0x4e, 0xb9, 0x5c, 0xe6, 0x50, 0x08, 0xe8, 0xd4, 0x74, 0xd1, 0x73,
	0x80, 0x70, 0xed, 0x40, 0xa4, 0x52, 0x69, 0x69, 0x32, 0x95, 0x94, 0xe3, 0x14, 0xa6, 0xf1, 0x08,
	0xc0, 0x74, 0x5f, 0x2f, 0x08, 0x5d, 0xf2, 0x78, 0x35, 0x50, 0xd7, 0xa1, 0x54, 0xcf, 0x6d, 0xbc,
	0x81, 0xa3, 0x24, 0xb5, 0xab, 0x71, 0xe9, 0x3c, 0xd5, 0x2b, 0xf2, 0xcc, 0xa5, 0xf2, 0x6c, 0xbc,
	0x85, 0x7b, 0x71, 0x3e, 0xd7, 0xba, 0xcd, 0x96, 0xa3, 0xee, 0x50, 0xce, 0x77, 0x70, 0x94, 0x72,
	0x1c, 0xad, 0x3d, 0x8b, 0x33, 0x8c, 0xea, 0xca, 0x49, 0x4e, 0x9e, 0x61, 0xb4, 0x87, 0xef, 0xcf,
	0xa0, 0x72, 0xad, 0xcb, 0xc6, 0x39, 0x1c, 0xa7, 0xbb, 0x75, 0x5d, 0xf4, 0xdb, 0x36, 0xec, 0xf7,
	0x50, 0xb3, 0x18, 0xf5, 0xfc, 0xe9, 0xda, 0xe7, 0x11, 0x14, 0xbe, 0xe7, 0xdf, 0xa2, 0x5d, 0x65,
	0x2c, 0x7f, 0xec, 0x51, 0xd5, 0x5f, 0x15, 0xa8, 0x27, 0x59, 0xef, 0x14, 0xe4, 0x96, 0xc9, 0x6f,
	0x24, 0x95, 0xdf, 0x21, 0xa9, 0x22, 0x14, 0x8c, 0x79, 0xc8, 0x96, 0x8d, 0x27, 0x50, 0x91, 0x29,
	0x45, 0x98, 0x44, 0x21, 0x1f, 0x3c, 0xd7, 0x61, 0x8e, 0xe8, 0x64, 0x19, 0x8b, 0xef, 0xc6, 0x3f,
	0x72, 0x90, 0x1f, 0x45, 0x84, 0x6e, 0xb1, 0xe7, 0x8a, 0x19, 0x69, 0xc2, 0x41, 0xc4, 0x1c, 0xb6,
	0x88, 0xe2, 0x51, 0x45, 0x32, 0x13, 0xc3, 0x67, 0x1e, 0x5b, 0x5a, 0x42, 0x83, 0x63, 0x04, 0x6a,
	0x41, 0x21, 0x7c, 0x1f, 0xf8, 0x24, 0x4e, 0xfa, 0xd1, 0xa9, 0x5c, 0x1c, 0xa7, 0xab, 0xc5, 0x71,
	0x2a, 0x93, 0x7b, 0xe3, 0xcc, 0x16, 0x04, 0x4b, 0x28, 0xb7, 0x21, 0x73, 0xc7, 0x9b, 0xd5, 0x0b,
	0xbb, 0xd8, 0x08, 0x28, 0xfa, 0x1a, 0x4a, 0xbc, 0x85, 0xbe, 0x33, 0x27, 0xf5, 0x83, 0x1d, 0xcc,
	0xd6, 0x68, 0x6e, 0x19, 0x3a, 0x51, 0xf4, 0x63, 0x40, 0xdd, 0x7a, 0x71, 0x17, 0xcb, 0x15, 0x1a,
	0x3d, 0x87, 0xbc, 0x88, 0x57, 0xda, 0xc1, 0x4a, 0x20, 0xd1, 0x43, 0x28, 0x4f, 0x28, 0x71, 0x18,
	0x19, 0x3b, 0xac, 0x5e, 0x16, 0x3d, 0x2d, 0x49, 0x81, 0xce, 0xb8, 0x72, 0x11, 0xba, 0xb1, 0x12,
	0xa4, 0x52, 0x0a, 0x74, 0xd6, 0xf8, 0x8b, 0x02, 0x68, 0x40, 0xa7, 0x6f, 0x3d, 0xf6, 0x3e, 0xe6,
	0x1a, 0xf3, 0x48, 0xb4, 0x75, 0x62, 0x28, 0x4e, 0x49, 0x15, 0x6c, 0x93, 0x41, 0x3f, 0x07, 0xcd,
	0x89, 0x4d, 0x96, 0xe3, 0x29, 0x0d, 0x16, 0xa1, 0x3c, 0xb8, 0x32, 0xbe, 0xbb, 0x96, 0x9f, 0x09,
	0x31, 0x3a, 0x81, 0x8a, 0x93, 0x78, 0x17, 0x67, 0x56, 0xc6, 0x69, 0x51, 0xe3, 0x02, 0xee, 0x72,
	0xaa, 0xf0, 0x3c, 0x06, 0x74, 0xca, 0x53, 0x41, 0x8f, 0x21, 0xcf, 0x9b, 0x29, 0xb2, 0xa8, 0xb4,
	0x40, 0x92, 0x81, 0x83, 0xb0, 0x90, 0xa3, 0x2f, 0xa1, 0x24, 0x58, 0xe4, 0x5f, 0x04, 0x75, 0xf5,
	0x24, 0xf7, 0xac, 0xd2, 0xaa, 0x4b, 0xcc, 0x76, 0x3d, 0xb8, 0xc8, 0x19, 0xe6, 0x5f, 0x04, 0x8d,
	0xf3, 0x4c, 0x1c, 0x2e, 0xba, 0x31, 0xce, 0x53, 0xc8, 0x07, 0x74, 0x1a, 0xc5, 0x31, 0xd0, 0x3a,
	0x86, 0xe3, 0x7b, 0x1f, 0xe5, 0x80, 0x08, 0x7d, 0xe3, 0x0f, 0x50, 0xe6, 0x56, 0x72, 0x1e, 0x1e,
	0xa7, 0xe6, 0x61, 0xc3, 0x29, 0x97, 0xef, 0xb1, 0x0e, 0xfe, 0xa9, 0x40, 0x35, 0x1d, 0xf5, 0xb2,
	0x33, 0x9a, 0x04, 0xee, 0xfa, 0x8c, 0xf8, 0x37, 0x7a, 0x0c, 0x15, 0xde, 0x23, 0x1a, 0xcc, 0x48,
	0x32, 0xfc, 0xe5, 0x80, 0x4e, 0x71, 0x30, 0x23, 0x66, 0x72, 0xae, 0xf9, 0xd4, 0xb9, 0x26, 0x63,
	0x58, 0xb8, 0x71, 0x0c, 0x33, 0xc4, 0x3b, 0xb8, 0x8e, 0x78, 0xc5, 0x0d, 0xe2, 0xfd, 0x5b, 0x01,
	0x2d, 0x5d, 0x8e, 0xe1, 0x7a, 0xec, 0x92, 0x6b, 0x26, 0x29, 0xe9, 0xc6, 0x49, 0x10, 0x05, 0xff,
	0x66, 0xbb, 0xe0, 0x4a, 0xeb, 0xe1, 0x96, 0xa1, 0xe9, 0xb3, 0xaf, 0x5e, 0x4a, 0xbb, 0x54, 0x37,
	0x9e, 0xa7, 0xba, 0xb1, 0xdb, 0xe0, 0xdd, 0xa2, 0x57, 0x0d, 0x17, 0x4a, 0x03, 0x1a, 0xaf, 0xcb,
	0xa7, 0x19, 0x7a, 0x5c, 0xca, 0xa9, 0x3d, 0x69, 0xf2, 0xdf, 0x1c, 0x14, 0x7b, 0x24, 0x8a, 0x9c,
	0x29, 0xd9, 0x6a, 0xe7, 0x2f, 0x20, 0xcf, 0x96, 0xa1, 0x6c, 0x67, 0xad, 0x75, 0x28, 0xfd, 0xc4,
	0x60, 0xf9, 0x18, 0xe2, 0x6a, 0xf4, 0x12, 0xaa, 0x94, 0x4c, 0x88, 0xf7, 0x03, 0x19, 0x0b, 0x78,
	0x2e, 0x0d, 0xc7, 0x52, 0x23, 0xe0, 0x15, 0x9a, 0xfc, 0x48, 0x2d, 0xf5, 0x7c, 0x7a, 0xa9, 0xa7,
	0xae, 0xa4, 0x42, 0xe6, 0x4a, 0xaa, 0x81, 0xca, 0x82, 0x98, 0x33, 0x2a, 0x0b, 0xf8, 0x76, 0x66,
	0x1e, 0x9b, 0x91, 0x9d, 0x96, 0xa5, 0x84, 0xa2, 0xaf, 0xa0, 0x38, 0x09, 0x7c, 0x46, 0x7c, 0xb6,
	0xd3, 0xb2, 0x5c, 0x81, 0x79, 0xac, 0x0b, 0x6f, 0x46, 0x22, 0xb1, 0x2b, 0x6f, 0x8c, 0x25, 0xa0,
	0xa9, 0xa3, 0x86, 0xdb, 0x8d, 0x45, 0xe5, 0xba, 0xb1, 0xa8, 0x66, 0xc7, 0x02, 0xfd, 0x0e, 0xaa,
	0x3c, 0x49, 0x67, 0xc2, 0xe4, 0x62, 0x3b, 0xda, 0x21, 0xc1, 0x4a, 0x6c, 0x21, 0x16, 0xdc, 0x3b,
	0xa8, 0xc4, 0x27, 0x2a, 0x88, 0xf6, 0x24, 0x43, 0xb4, 0x3b, 0x99, 0x23, 0xdf, 0x9b, 0x63, 0x7f,
	0xcb, 0x41, 0x09, 0x93, 0xd9, 0xe5, 0x6b, 0xe8, 0x21, 0x94, 0xa3, 0x60, 0x41, 0x27, 0x24, 0xb9,
	0xdf, 0x4b, 0x52, 0x60, 0x0a, 0x25, 0x73, 0xe8, 0x94, 0xb0, 0x64, 0x1b, 0x95, 0xa4, 0xc0, 0x74,
	0xf9, 0x50, 0x08, 0xbe, 0xe5, 0xd3, 0xfd, 0x5d, 0xc5, 0x49, 0xf1, 0xf3, 0x09, 0x54, 0x1d, 0xc6,
	0x9c, 0xc9, 0x7b, 0xe2, 0x8e, 0x3d, 0xf7, 0x45, 0xcc, 0xab, 0xca, 0x4a, 0x66, 0xba, 0x2f, 0x36,
	0x20, 0xad, 0x98, 0x66, 0x29, 0x48, 0x0b, 0xbd, 0x84, 0x83, 0x1f, 0x78, 0xfb, 0x5e, 0xec, 0x44,
	0xb8, 0x18, 0xbb, 0xb6, 0x6a, 0xed, 0x44, 0xb8, 0x18, 0x9b, 0xe2, 0x4e, 0xf9, 0x76, 0xdc, 0x81,
	0xeb, 0xb8, 0x53, 0xd9, 0x58, 0xa9, 0x01, 0xdc, 0x59, 0x75, 0x4b, 0x6e, 0x99, 0x5f, 0x43, 0x99,
	0xae, 0x04, 0x31, 0x03, 0x6a, 0xd9, 0xae, 0xe2, 0x04, 0xb0, 0xcf, 0xae, 0x51, 0xa0, 0x3a, 0x74,
	0x28, 0xf3, 0x57, 0xb7, 0xde, 0xff, 0x39, 0x20, 0xfa, 0x46, 0xbe, 0xc6, 0xc6, 0x73, 0x27, 0xac,
	0xe7, 0x84, 0xfb, 0xcf, 0x56, 0xf8, 0x24, 0x0b, 0x71, 0xcd, 0xf6, 0x9c, 0xd0, 0xf0, 0x19, 0x5d,
	0x62, 0xb1, 0x7d, 0x7a, 0x4e, 0xf8, 0xe9, 0x6b, 0xa8, 0xa6, 0x15, 0xfc, 0xe9, 0xff, 0x81, 0x2c,
	0x57, 0x7f, 0x3c, 0x7e, 0x20, 0x4b, 0xf4, 0x2b, 0x28, 0x88, 0xf3, 0x8a, 0x53, 0x39, 0x4e, 0x2e,
	0xed, 0xd4, 0x73, 0x01, 0x4b, 0xcc, 0x37, 0xea, 0xd7, 0x4a, 0xe3, 0xef, 0x2a, 0xd4, 0x3a, 0x24,
	0x74, 0x28, 0x9b, 0x13, 0x9f, 0x5d, 0x7a, 0x83, 0x69, 0x90, 0x0b, 0xd7, 0x73, 0xc0, 0x3f, 0xaf,
	0x7e, 0x8a, 0xdf, 0xf6, 0xee, 0xf9, 0x2d, 0x54, 0x5c, 0x12, 0x4d, 0xa8, 0x17, 0x8a, 0xfe, 0xed,
	0xf2, 0xa8, 0x4d, 0x1b, 0x70, 0x2a, 0x53, 0x32, 0x77, 0xe8, 0x87, 0x9d, 0x1e, 0xb6, 0x31, 0x36,
	0x45, 0xe5, 0xe2, 0x8d, 0x37, 0xde, 0x7f, 0x14, 0x80, 0xa4, 0x3f, 0xfb, 0xf7, 0xe6, 0xb2, 0x57,
	0xca, 0xc9, 0x76, 0xf5, 0xe5, 0x6c, 0x7d, 0xf7, 0x33, 0xf5, 0x95, 0xf7, 0xa9, 0x20, 0x3b, 0x8c,
	0xa5, 0xeb, 0x86, 0xb1, 0xbc, 0x31, 0x8c, 0x13, 0x28, 0x77, 0x48, 0xc8, 0xe4, 0x5c, 0xfc, 0x3c,
	0xb3, 0x85, 0x63, 0x8e, 0x27, 0x9d, 0xd9, 0x77, 0x11, 0x37, 0xff, 0xa5, 0x40, 0x35, 0x9d, 0x37,
	0xba, 0x0f, 0xc8, 0xe8, 0xdb, 0xa6, 0x7d, 0x3e, 0xb6, 0x6c, 0xdd, 0x1e, 0x59, 0xe3, 0xfe, 0xa8,
	0xdb, 0xd5, 0x7e, 0x82, 0xea, 0x70, 0xb4, 0x21, 0x1f, 0xe0, 0x9e, 0xde, 0xd5, 0x14, 0xf4, 0x09,
	0x1c, 0x67, 0x35, 0x1d, 0xa3, 0x6b, 0xd8, 0x46, 0x47, 0x53, 0xd1, 0x4f, 0xe1, 0x93, 0xac, 0xca,
	0xec, 0xeb, 0x6d, 0xdb, 0x7c, 0xa3, 0x73, 0x75, 0x0e, 0x3d, 0x82, 0xfa, 0xa6, 0xe5, 0x10, 0x1b,
	0x6d, 0xa1, 0xcd, 0xa3, 0x87, 0xf0, 0x20, 0xab, 0xb5, 0x46, 0xdf, 0xf6, 0x4c, 0x9b, 0x2b, 0x0b,
	0xdb, 0xa6, 0x43, 0x3c, 0x68, 0x1b, 0x96, 0x65, 0xf6, 0xcf, 0xb4, 0x83, 0xed, 0x22, 0x3a, 0x83,
	0xbe, 0xa1, 0x15, 0x9b, 0x9f, 0x43, 0xa9, 0xeb, 0xf8, 0xd3, 0x05, 0x7f, 0xda, 0xdc, 0x81, 0x72,
	0x57, 0xef, 0x9f, 0xad, 0xea, 0xab, 0x01, 0x88, 0x9f, 0xdf, 0xbd, 0x1a, 0xb7, 0xfb, 0x9a, 0xd2,
	0x3c, 0x85, 0x62, 0x3b, 0x58, 0xc4, 0x73, 0x5e, 0x6d, 0x0f, 0x46, 0x7d, 0x1b, 0x9f, 0xaf, 0xc0,
	0x87, 0x70, 0x67, 0x25, 0x69, 0xbf, 0x32, 0xfb, 0xba, 0xa6, 0x34, 0xcf, 0xa0, 0xc4, 0xff, 0x5c,
	0x10, 0x0f, 0x19, 0x04, 0x35, 0x7d, 0x64, 0xbf, 0x1a, 0xdb, 0xe7, 0x43, 0x63, 0x65, 0x92, 0x91,
	0x61, 0x43, 0xef, 0x68, 0x0a, 0xba, 0x07, 0x77, 0x13, 0xd9, 0x5b, 0x6c, 0xda, 0x86, 0xa6, 0x36,
	0x2d, 0x80, 0x91, 0xa0, 0x80, 0x70, 0x75, 0x04, 0xda, 0x68, 0xd8, 0xd1, 0x6d, 0x23, 0xe3, 0xec,
	0x01, 0xdc, 0x4b, 0x4b, 0xb1, 0x31, 0xec, 0xea, 0x6d, 0x43, 0x53, 0x78, 0xe1, 0x69, 0x85, 0x3e,
	0x1c, 0x1a, 0xfd, 0x8e, 0xa6, 0x36, 0xff, 0x0c, 0xa5, 0xd5, 0xff, 0xab, 0x78, 0x26, 0xd6, 0x00,
	0xdb, 0x19, 0x87, 0xf7, 0x01, 0x25, 0x32, 0xdb, 0xec, 0x19, 0x63, 0xdd, 0x6a, 0x6b, 0x0a, 0x0f,
	0xb4, 0x21, 0xef, 0x18, 0x56, 0x5b, 0x53, 0x79, 0x5e, 0x89, 0xc2, 0xec, 0x08, 0x78, 0x0e, 0x1d,
	0xc3, 0x61, 0x46, 0x2a, 0xc0, 0xf9, 0xe6, 0xeb, 0xf5, 0x8b, 0x22, 0x7e, 0xe7, 0x1d, 0xf6, 0x0c,
	0xcb, 0xd2, 0xcf, 0xb2, 0x45, 0x1d, 0x81, 0x96, 0x11, 0x0f, 0xf0, 0x99, 0xa6, 0x6c, 0x81, 0x47,
	0x96, 0x81, 0x35, 0xb5, 0xe9, 0x41, 0x05, 0x67, 0x9e, 0x8e, 0x87, 0xd8, 0x68, 0x1b, 0xe6, 0x9b,
	0xac, 0xcb, 0x4d, 0xb1, 0xc5, 0x5b, 0x2c, 0xba, 0x94, 0x11, 0x1b, 0x3d, 0xdd, 0xec, 0xca, 0xa2,
	0xb2, 0xf0, 0x9e, 0xa5, 0xe5, 0x9a, 0x14, 0xaa, 0xe9, 0x27, 0x04, 0x3f, 0x7c, 0x6c, 0x74, 0x75,
	0xdb, 0x1c, 0xf4, 0x57, 0x71, 0x9e, 0x42, 0x63, 0x2d, 0x1a, 0xe0, 0x33, 0x91, 0xe4, 0x78, 0xa8,
	0x63, 0xbb, 0x6f, 0xe0, 0xb1, 0x35, 0x1a, 0x0e, 0xbb, 0xa6, 0x81, 0x35, 0x05, 0xfd, 0x12, 0x7e,
	0x76, 0x35, 0xae, 0x3b, 0x38, 0x33, 0x2d, 0xdb, 0x6c, 0x5b, 0x9a, 0xfa, 0xed, 0x03, 0x38, 0x9e,
	0x04, 0xf3, 0xd3, 0x77, 0x41, 0xc0, 0x9c, 0x30, 0x94, 0x13, 0x3c, 0xa5, 0xe1, 0xe4, 0xdd, 0x81,
	0x58, 0xad, 0x5f, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x64, 0xd6, 0xf6, 0x72, 0x00, 0x15, 0x00,
	0x00,
}
