// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dal_sys_auth.proto

package core

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReadSysAuthoritiesReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId                int64    `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	QueryAuthorityGroups []int64  `protobuf:"varint,3,rep,packed,name=query_authority_groups,json=queryAuthorityGroups,proto3" json:"query_authority_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadSysAuthoritiesReq) Reset()         { *m = ReadSysAuthoritiesReq{} }
func (m *ReadSysAuthoritiesReq) String() string { return proto.CompactTextString(m) }
func (*ReadSysAuthoritiesReq) ProtoMessage()    {}
func (*ReadSysAuthoritiesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_569dfa7a95b75065, []int{0}
}

func (m *ReadSysAuthoritiesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadSysAuthoritiesReq.Unmarshal(m, b)
}
func (m *ReadSysAuthoritiesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadSysAuthoritiesReq.Marshal(b, m, deterministic)
}
func (m *ReadSysAuthoritiesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadSysAuthoritiesReq.Merge(m, src)
}
func (m *ReadSysAuthoritiesReq) XXX_Size() int {
	return xxx_messageInfo_ReadSysAuthoritiesReq.Size(m)
}
func (m *ReadSysAuthoritiesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadSysAuthoritiesReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadSysAuthoritiesReq proto.InternalMessageInfo

func (m *ReadSysAuthoritiesReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ReadSysAuthoritiesReq) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *ReadSysAuthoritiesReq) GetQueryAuthorityGroups() []int64 {
	if m != nil {
		return m.QueryAuthorityGroups
	}
	return nil
}

type SysAuthorities struct {
	AuthorityGroups      []*SysAuthorityGroup `protobuf:"bytes,1,rep,name=authority_groups,json=authorityGroups,proto3" json:"authority_groups,omitempty"`
	Authorities          []*SysAuthority      `protobuf:"bytes,2,rep,name=authorities,proto3" json:"authorities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *SysAuthorities) Reset()         { *m = SysAuthorities{} }
func (m *SysAuthorities) String() string { return proto.CompactTextString(m) }
func (*SysAuthorities) ProtoMessage()    {}
func (*SysAuthorities) Descriptor() ([]byte, []int) {
	return fileDescriptor_569dfa7a95b75065, []int{1}
}

func (m *SysAuthorities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysAuthorities.Unmarshal(m, b)
}
func (m *SysAuthorities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysAuthorities.Marshal(b, m, deterministic)
}
func (m *SysAuthorities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysAuthorities.Merge(m, src)
}
func (m *SysAuthorities) XXX_Size() int {
	return xxx_messageInfo_SysAuthorities.Size(m)
}
func (m *SysAuthorities) XXX_DiscardUnknown() {
	xxx_messageInfo_SysAuthorities.DiscardUnknown(m)
}

var xxx_messageInfo_SysAuthorities proto.InternalMessageInfo

func (m *SysAuthorities) GetAuthorityGroups() []*SysAuthorityGroup {
	if m != nil {
		return m.AuthorityGroups
	}
	return nil
}

func (m *SysAuthorities) GetAuthorities() []*SysAuthority {
	if m != nil {
		return m.Authorities
	}
	return nil
}

type SysAuthority struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Value                int64    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysAuthority) Reset()         { *m = SysAuthority{} }
func (m *SysAuthority) String() string { return proto.CompactTextString(m) }
func (*SysAuthority) ProtoMessage()    {}
func (*SysAuthority) Descriptor() ([]byte, []int) {
	return fileDescriptor_569dfa7a95b75065, []int{2}
}

func (m *SysAuthority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysAuthority.Unmarshal(m, b)
}
func (m *SysAuthority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysAuthority.Marshal(b, m, deterministic)
}
func (m *SysAuthority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysAuthority.Merge(m, src)
}
func (m *SysAuthority) XXX_Size() int {
	return xxx_messageInfo_SysAuthority.Size(m)
}
func (m *SysAuthority) XXX_DiscardUnknown() {
	xxx_messageInfo_SysAuthority.DiscardUnknown(m)
}

var xxx_messageInfo_SysAuthority proto.InternalMessageInfo

func (m *SysAuthority) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SysAuthority) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *SysAuthority) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *SysAuthority) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SysAuthorityGroup struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid                  int64    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Value                int64    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SysAuthorityGroup) Reset()         { *m = SysAuthorityGroup{} }
func (m *SysAuthorityGroup) String() string { return proto.CompactTextString(m) }
func (*SysAuthorityGroup) ProtoMessage()    {}
func (*SysAuthorityGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_569dfa7a95b75065, []int{3}
}

func (m *SysAuthorityGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SysAuthorityGroup.Unmarshal(m, b)
}
func (m *SysAuthorityGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SysAuthorityGroup.Marshal(b, m, deterministic)
}
func (m *SysAuthorityGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SysAuthorityGroup.Merge(m, src)
}
func (m *SysAuthorityGroup) XXX_Size() int {
	return xxx_messageInfo_SysAuthorityGroup.Size(m)
}
func (m *SysAuthorityGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_SysAuthorityGroup.DiscardUnknown(m)
}

var xxx_messageInfo_SysAuthorityGroup proto.InternalMessageInfo

func (m *SysAuthorityGroup) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SysAuthorityGroup) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *SysAuthorityGroup) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *SysAuthorityGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ReadSysAuthoritiesReq)(nil), "core.ReadSysAuthoritiesReq")
	proto.RegisterType((*SysAuthorities)(nil), "core.SysAuthorities")
	proto.RegisterType((*SysAuthority)(nil), "core.SysAuthority")
	proto.RegisterType((*SysAuthorityGroup)(nil), "core.SysAuthorityGroup")
}

func init() { proto.RegisterFile("dal_sys_auth.proto", fileDescriptor_569dfa7a95b75065) }

var fileDescriptor_569dfa7a95b75065 = []byte{
	// 334 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcb, 0x4e, 0xeb, 0x30,
	0x10, 0x86, 0x4f, 0xe2, 0x5e, 0x0e, 0x53, 0x54, 0xda, 0x51, 0x4b, 0x03, 0x6c, 0xaa, 0xac, 0xba,
	0xca, 0xa2, 0xf4, 0x05, 0xa8, 0x90, 0x50, 0xb6, 0xee, 0x9e, 0xc8, 0x8d, 0xad, 0x34, 0xa2, 0xc5,
	0xa9, 0x93, 0x54, 0xca, 0x82, 0x17, 0xe0, 0xa9, 0x91, 0x27, 0xd0, 0x8b, 0xc2, 0x82, 0xdd, 0x8c,
	0x67, 0xfc, 0x7f, 0x9e, 0xdf, 0x03, 0x28, 0xc5, 0x36, 0xca, 0xab, 0x3c, 0x12, 0x65, 0xb1, 0x09,
	0x32, 0xa3, 0x0b, 0x8d, 0xad, 0x58, 0x1b, 0xe5, 0x7f, 0xc0, 0x98, 0x2b, 0x21, 0x57, 0x55, 0xfe,
	0x54, 0x16, 0x1b, 0x6d, 0xd2, 0x22, 0x55, 0x39, 0x57, 0x7b, 0x9c, 0x40, 0xb7, 0xcc, 0x95, 0x89,
	0x52, 0xe9, 0x39, 0x53, 0x67, 0xc6, 0x78, 0xc7, 0xa6, 0xa1, 0xc4, 0x31, 0x74, 0xb4, 0x49, 0xec,
	0xb9, 0x4b, 0xe7, 0x6d, 0x6d, 0x92, 0x50, 0xe2, 0x02, 0x6e, 0xf7, 0xa5, 0x32, 0x15, 0x21, 0xac,
	0x4e, 0x15, 0x25, 0x46, 0x97, 0x59, 0xee, 0xb1, 0x29, 0x9b, 0x31, 0x3e, 0xa2, 0xea, 0x0f, 0xa4,
	0x7a, 0xa1, 0x9a, 0xff, 0xe9, 0x40, 0xff, 0x92, 0x8d, 0x4b, 0x18, 0x34, 0x24, 0x9c, 0x29, 0x9b,
	0xf5, 0xe6, 0x93, 0xc0, 0x3e, 0x39, 0x38, 0xeb, 0xaf, 0x65, 0xf8, 0x8d, 0xb8, 0x94, 0xc5, 0x05,
	0xf4, 0xc4, 0x49, 0xd2, 0x73, 0xe9, 0x3a, 0x36, 0xaf, 0xf3, 0xf3, 0x36, 0x5f, 0xc1, 0xf5, 0x79,
	0x11, 0x07, 0xc0, 0xde, 0x54, 0x45, 0xe3, 0x5f, 0x71, 0x1b, 0xe2, 0x1d, 0xfc, 0xa7, 0x17, 0x9d,
	0xa6, 0xef, 0x52, 0x1e, 0x4a, 0x1c, 0x41, 0xfb, 0x20, 0xb6, 0xa5, 0xf2, 0x58, 0xed, 0x0a, 0x25,
	0x88, 0xd0, 0x7a, 0x17, 0x3b, 0xe5, 0xb5, 0x48, 0x83, 0x62, 0x3f, 0x82, 0x61, 0x63, 0x04, 0xec,
	0x83, 0x7b, 0x74, 0xda, 0x4d, 0xa5, 0x65, 0x67, 0x47, 0x88, 0x0d, 0xff, 0x0e, 0x98, 0xbf, 0xc2,
	0xf0, 0x59, 0x6c, 0xbf, 0x19, 0x2b, 0x65, 0x0e, 0x69, 0xac, 0x30, 0x04, 0x6c, 0x7e, 0x34, 0x3e,
	0xd4, 0x9e, 0xfc, 0xba, 0x02, 0xf7, 0xa3, 0x86, 0x61, 0xd6, 0xa5, 0x7f, 0xcb, 0x09, 0x8c, 0x63,
	0xbd, 0x0b, 0xd6, 0x5a, 0x17, 0x22, 0xcb, 0xea, 0xa6, 0xc4, 0x64, 0xf1, 0xba, 0x43, 0x9b, 0xf5,
	0xf8, 0x15, 0x00, 0x00, 0xff, 0xff, 0x75, 0x7a, 0xa2, 0xb8, 0x6f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DalSysAuthServiceClient is the client API for DalSysAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DalSysAuthServiceClient interface {
	ReadSysAuthorities(ctx context.Context, in *ReadSysAuthoritiesReq, opts ...grpc.CallOption) (*SysAuthorities, error)
}

type dalSysAuthServiceClient struct {
	cc *grpc.ClientConn
}

func NewDalSysAuthServiceClient(cc *grpc.ClientConn) DalSysAuthServiceClient {
	return &dalSysAuthServiceClient{cc}
}

func (c *dalSysAuthServiceClient) ReadSysAuthorities(ctx context.Context, in *ReadSysAuthoritiesReq, opts ...grpc.CallOption) (*SysAuthorities, error) {
	out := new(SysAuthorities)
	err := c.cc.Invoke(ctx, "/core.DalSysAuthService/ReadSysAuthorities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DalSysAuthServiceServer is the server API for DalSysAuthService service.
type DalSysAuthServiceServer interface {
	ReadSysAuthorities(context.Context, *ReadSysAuthoritiesReq) (*SysAuthorities, error)
}

func RegisterDalSysAuthServiceServer(s *grpc.Server, srv DalSysAuthServiceServer) {
	s.RegisterService(&_DalSysAuthService_serviceDesc, srv)
}

func _DalSysAuthService_ReadSysAuthorities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSysAuthoritiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DalSysAuthServiceServer).ReadSysAuthorities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.DalSysAuthService/ReadSysAuthorities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DalSysAuthServiceServer).ReadSysAuthorities(ctx, req.(*ReadSysAuthoritiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DalSysAuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "core.DalSysAuthService",
	HandlerType: (*DalSysAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadSysAuthorities",
			Handler:    _DalSysAuthService_ReadSysAuthorities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dal_sys_auth.proto",
}
