// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dal_auth.proto

package core

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReadAuthoritiesReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrgId                int64    `protobuf:"varint,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	QueryAuthorityGroups []int64  `protobuf:"varint,3,rep,packed,name=query_authority_groups,json=queryAuthorityGroups,proto3" json:"query_authority_groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadAuthoritiesReq) Reset()         { *m = ReadAuthoritiesReq{} }
func (m *ReadAuthoritiesReq) String() string { return proto.CompactTextString(m) }
func (*ReadAuthoritiesReq) ProtoMessage()    {}
func (*ReadAuthoritiesReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1be496d0d735f64, []int{0}
}

func (m *ReadAuthoritiesReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadAuthoritiesReq.Unmarshal(m, b)
}
func (m *ReadAuthoritiesReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadAuthoritiesReq.Marshal(b, m, deterministic)
}
func (m *ReadAuthoritiesReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadAuthoritiesReq.Merge(m, src)
}
func (m *ReadAuthoritiesReq) XXX_Size() int {
	return xxx_messageInfo_ReadAuthoritiesReq.Size(m)
}
func (m *ReadAuthoritiesReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadAuthoritiesReq.DiscardUnknown(m)
}

var xxx_messageInfo_ReadAuthoritiesReq proto.InternalMessageInfo

func (m *ReadAuthoritiesReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ReadAuthoritiesReq) GetOrgId() int64 {
	if m != nil {
		return m.OrgId
	}
	return 0
}

func (m *ReadAuthoritiesReq) GetQueryAuthorityGroups() []int64 {
	if m != nil {
		return m.QueryAuthorityGroups
	}
	return nil
}

type Authorities struct {
	AuthorityGroups      []*AuthorityGroup `protobuf:"bytes,1,rep,name=authority_groups,json=authorityGroups,proto3" json:"authority_groups,omitempty"`
	Authorities          []*Authority      `protobuf:"bytes,2,rep,name=authorities,proto3" json:"authorities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Authorities) Reset()         { *m = Authorities{} }
func (m *Authorities) String() string { return proto.CompactTextString(m) }
func (*Authorities) ProtoMessage()    {}
func (*Authorities) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1be496d0d735f64, []int{1}
}

func (m *Authorities) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authorities.Unmarshal(m, b)
}
func (m *Authorities) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authorities.Marshal(b, m, deterministic)
}
func (m *Authorities) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authorities.Merge(m, src)
}
func (m *Authorities) XXX_Size() int {
	return xxx_messageInfo_Authorities.Size(m)
}
func (m *Authorities) XXX_DiscardUnknown() {
	xxx_messageInfo_Authorities.DiscardUnknown(m)
}

var xxx_messageInfo_Authorities proto.InternalMessageInfo

func (m *Authorities) GetAuthorityGroups() []*AuthorityGroup {
	if m != nil {
		return m.AuthorityGroups
	}
	return nil
}

func (m *Authorities) GetAuthorities() []*Authority {
	if m != nil {
		return m.Authorities
	}
	return nil
}

type Authority struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	GroupId              int64    `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Value                int64    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Authority) Reset()         { *m = Authority{} }
func (m *Authority) String() string { return proto.CompactTextString(m) }
func (*Authority) ProtoMessage()    {}
func (*Authority) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1be496d0d735f64, []int{2}
}

func (m *Authority) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authority.Unmarshal(m, b)
}
func (m *Authority) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authority.Marshal(b, m, deterministic)
}
func (m *Authority) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authority.Merge(m, src)
}
func (m *Authority) XXX_Size() int {
	return xxx_messageInfo_Authority.Size(m)
}
func (m *Authority) XXX_DiscardUnknown() {
	xxx_messageInfo_Authority.DiscardUnknown(m)
}

var xxx_messageInfo_Authority proto.InternalMessageInfo

func (m *Authority) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Authority) GetGroupId() int64 {
	if m != nil {
		return m.GroupId
	}
	return 0
}

func (m *Authority) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Authority) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type AuthorityGroup struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pid                  int64    `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	Value                int64    `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorityGroup) Reset()         { *m = AuthorityGroup{} }
func (m *AuthorityGroup) String() string { return proto.CompactTextString(m) }
func (*AuthorityGroup) ProtoMessage()    {}
func (*AuthorityGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_c1be496d0d735f64, []int{3}
}

func (m *AuthorityGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorityGroup.Unmarshal(m, b)
}
func (m *AuthorityGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorityGroup.Marshal(b, m, deterministic)
}
func (m *AuthorityGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorityGroup.Merge(m, src)
}
func (m *AuthorityGroup) XXX_Size() int {
	return xxx_messageInfo_AuthorityGroup.Size(m)
}
func (m *AuthorityGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorityGroup.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorityGroup proto.InternalMessageInfo

func (m *AuthorityGroup) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *AuthorityGroup) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *AuthorityGroup) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *AuthorityGroup) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ReadAuthoritiesReq)(nil), "core.ReadAuthoritiesReq")
	proto.RegisterType((*Authorities)(nil), "core.Authorities")
	proto.RegisterType((*Authority)(nil), "core.Authority")
	proto.RegisterType((*AuthorityGroup)(nil), "core.AuthorityGroup")
}

func init() { proto.RegisterFile("dal_auth.proto", fileDescriptor_c1be496d0d735f64) }

var fileDescriptor_c1be496d0d735f64 = []byte{
	// 324 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbb, 0x6f, 0xc2, 0x30,
	0x10, 0xc6, 0x9b, 0x98, 0x47, 0x39, 0xa4, 0x40, 0x4f, 0x50, 0xd2, 0x4e, 0x28, 0x13, 0x53, 0xa4,
	0xd2, 0xee, 0x7d, 0xa8, 0x52, 0xc5, 0xea, 0xae, 0x95, 0x90, 0x89, 0xad, 0x10, 0x15, 0xea, 0x60,
	0x62, 0xa4, 0x74, 0xeb, 0x7f, 0x5e, 0xf9, 0x50, 0x03, 0x81, 0xa5, 0xdb, 0x9d, 0xcf, 0xf7, 0xfb,
	0xce, 0xdf, 0x19, 0x02, 0x29, 0x56, 0x73, 0x61, 0x8b, 0x65, 0x9c, 0x1b, 0x5d, 0x68, 0x6c, 0x24,
	0xda, 0xa8, 0xe8, 0x1b, 0x90, 0x2b, 0x21, 0x9f, 0x6d, 0xb1, 0xd4, 0x26, 0x2b, 0x32, 0xb5, 0xe5,
	0x6a, 0x83, 0x23, 0x68, 0xdb, 0xad, 0x32, 0xf3, 0x4c, 0x86, 0xde, 0xd8, 0x9b, 0x30, 0xde, 0x72,
	0xe9, 0x4c, 0xe2, 0x10, 0x5a, 0xda, 0xa4, 0xee, 0xdc, 0xa7, 0xf3, 0xa6, 0x36, 0xe9, 0x4c, 0xe2,
	0x03, 0x5c, 0x6f, 0xac, 0x32, 0x25, 0xf1, 0x1d, 0xa7, 0x9c, 0xa7, 0x46, 0xdb, 0x7c, 0x1b, 0xb2,
	0x31, 0x9b, 0x30, 0x3e, 0xa0, 0xea, 0x9f, 0x48, 0xf9, 0x46, 0xb5, 0xe8, 0xc7, 0x83, 0xee, 0x91,
	0x30, 0x3e, 0x42, 0xff, 0xac, 0xdf, 0x1b, 0xb3, 0x49, 0x77, 0x3a, 0x88, 0xdd, 0xb0, 0x71, 0x1d,
	0xc0, 0x7b, 0xa2, 0x0e, 0xc4, 0x3b, 0xe8, 0x8a, 0x03, 0x2f, 0xf4, 0xa9, 0xb7, 0x77, 0xd2, 0xcb,
	0x8f, 0xef, 0x44, 0x0b, 0xe8, 0x54, 0x15, 0xec, 0x03, 0xfb, 0x54, 0x25, 0x3d, 0xb9, 0xc3, 0x5d,
	0x88, 0x37, 0x70, 0x49, 0x83, 0x1c, 0x5e, 0xdc, 0xa6, 0x7c, 0x26, 0x71, 0x00, 0xcd, 0x9d, 0x58,
	0x59, 0x15, 0xb2, 0xbd, 0x13, 0x94, 0x20, 0x42, 0xe3, 0x4b, 0xac, 0x55, 0xd8, 0x20, 0x06, 0xc5,
	0xd1, 0x07, 0x04, 0xf5, 0xc9, 0x31, 0x00, 0xbf, 0xb2, 0xd6, 0xcf, 0xa4, 0x13, 0xce, 0x2b, 0x05,
	0x17, 0xfe, 0x9f, 0x3e, 0xe5, 0x10, 0xbc, 0x8a, 0x95, 0x13, 0x78, 0x57, 0x66, 0x97, 0x25, 0x0a,
	0x9f, 0xa0, 0x77, 0xb2, 0x53, 0x0c, 0xf7, 0x26, 0x9c, 0xaf, 0xfa, 0xf6, 0xaa, 0x6e, 0x8f, 0xf3,
	0xe4, 0xe2, 0x65, 0x04, 0xc3, 0x44, 0xaf, 0xe3, 0x85, 0xd6, 0x85, 0xc8, 0xf3, 0xfd, 0x8d, 0xd4,
	0xe4, 0xc9, 0xa2, 0x45, 0x7f, 0xe7, 0xfe, 0x37, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x18, 0xd9, 0xdd,
	0x4d, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DalAuthServiceClient is the client API for DalAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DalAuthServiceClient interface {
	ReadAuthorities(ctx context.Context, in *ReadAuthoritiesReq, opts ...grpc.CallOption) (*Authorities, error)
}

type dalAuthServiceClient struct {
	cc *grpc.ClientConn
}

func NewDalAuthServiceClient(cc *grpc.ClientConn) DalAuthServiceClient {
	return &dalAuthServiceClient{cc}
}

func (c *dalAuthServiceClient) ReadAuthorities(ctx context.Context, in *ReadAuthoritiesReq, opts ...grpc.CallOption) (*Authorities, error) {
	out := new(Authorities)
	err := c.cc.Invoke(ctx, "/core.DalAuthService/ReadAuthorities", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DalAuthServiceServer is the server API for DalAuthService service.
type DalAuthServiceServer interface {
	ReadAuthorities(context.Context, *ReadAuthoritiesReq) (*Authorities, error)
}

func RegisterDalAuthServiceServer(s *grpc.Server, srv DalAuthServiceServer) {
	s.RegisterService(&_DalAuthService_serviceDesc, srv)
}

func _DalAuthService_ReadAuthorities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAuthoritiesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DalAuthServiceServer).ReadAuthorities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/core.DalAuthService/ReadAuthorities",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DalAuthServiceServer).ReadAuthorities(ctx, req.(*ReadAuthoritiesReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DalAuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "core.DalAuthService",
	HandlerType: (*DalAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReadAuthorities",
			Handler:    _DalAuthService_ReadAuthorities_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dal_auth.proto",
}
